In [1]:
# Adding required libraries
import pandas as pd
from datetime import  datetime
import xml.etree.ElementTree as ET

In [2]:
# Change required File path
file_path = "File.xls"

In [3]:
# Parse the xml file
xml = ET.parse(file_path)
root = xml.getroot()

In [4]:
# Parse the xml data to list
data = []
dtype = []
# Extract data from the XML structure
for row in root.findall('.//{urn:schemas-microsoft-com:office:spreadsheet}Row'):
    row_data = []
    dtype = []findall('data.append(row_data)
col_names = data[0]
data = data[1:]{urn:schemas-microsoft-com:office:spreadsheet}Cell'):
        data_type = cell.find('{urn:schemas-microsoft-com:office:spreadsheet}Data').get('{urn:schemas-microsoft-com:office:spreadsheet}Type')
        cell_value = cell.find('{urn:schemas-microsoft-com:office:spreadsheet}Data').text
        row_data.append(cell_value)
        dtype.append(data_type)
    
    for cell in row.

In [5]:
# Mapping the data types
d_dict = {}
map_type = {'String': str, 'Boolean': bool, 'Number': float, 'DateTime': 'datetime64[ns]'}
for ind, d_type in enumerate(dtype):
    d_dict[col_names[ind]] = map_type[d_type]

In [6]:
# Creating pandas DF
df = pd.DataFrame(
    data=data, 
    columns=col_names
).astype(d_dict)

In [8]:
# Checking th schema
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Number                  16 non-null     object
 1   Summary                 16 non-null     object
 2   Date                    16 non-null     datetime64[ns]
 3   Type                    16 non-null     object
 4   External?               16 non-null     bool
 5   Budget Cost             16 non-null     float64
 6   Budget Hours            16 non-null     float64
 7   Line Item Amount        16 non-null     float64
 8   Cost Rate Override      16 non-null     float64
 9   Actual Cost             16 non-null     object
 10  Gross Profit (%)        16 non-null     float64
 11  Assignee                16 non-null     object
 12  Estimated Start Date    16 non-null     object
 13  Estimated End Date      16 non-null     object
 14  Actual Start Date       16 non-null     object
 15  Actual Completion Date  16 non-null     datetime64[ns]
 16  Completed By            16 non-null     object
 17  Category Code           16 non-null     object
dtypes: bool(1), datetime64[ns](2), float64(5), object(10)
memory usage: 2.3+ KB

In [7]:
# Checking the sample data
df.head()

,Number,Summary,Date,Type,External?,Budget Cost,Budget Hours,Line Item Amount,Cost Rate Override,Actual Cost,Gross Profit (%),Assignee,Estimated Start Date,Estimated End Date,Actual Start Date,Actual Completion Date,Completed By,Category Code
0,"WO0001, Complete",Materials,2022-08-29 11:18:00,WO,True,12880.0,8.0,16100.0,80.0,None,20.0,None,08/29/2022,08/29/2022,None,2022-08-29 10:20:12.907,"Dehnke, Josh",MAT
1,"WO0002, Complete",Profit 1/2,2022-08-29 11:20:00,WO,True,0.0,8.0,3602.0,0.0,None,100.0,None,08/29/2022,08/29/2022,None,2022-10-21 14:50:32.230,"Dehnke, Josh",PROFIT
2,"WO0004, Complete",Overhead First 1/2,2022-08-29 11:22:00,WO,True,0.0,8.0,2401.5,0.0,None,100.0,None,08/29/2022,08/29/2022,None,2022-10-21 14:52:33.473,"Dehnke, Josh",Overhead
3,"WO0005, Complete",Design Fee,2022-08-29 11:23:00,WO,True,0.0,8.0,1600.0,0.0,None,100.0,None,08/29/2022,08/29/2022,None,2022-10-21 14:50:32.200,"Dehnke, Josh",Design
4,"WO0006, Complete",Planning Fee,2022-08-29 11:36:00,WO,True,1000.0,8.0,1000.0,100.0,None,0.0,None,08/29/2022,08/29/2022,None,2022-10-21 14:50:32.183,"Dehnke, Josh",Planning